plugins {
	id 'java-gradle-plugin'
	id 'com.gradle.plugin-publish' version '1.2.1'
	id 'com.palantir.git-version' version '0.13.0'
}

group = 'foo.zaaarf'
version = versionDetails().lastTag

gradlePlugin {
	plugins {
		zipdist {
			id = 'foo.zaaarf.zipdist'
			displayName = 'zipdist'
			description = 'Produces a ZIP containing all the things necessary for manual Maven publishing.'
			tags.addAll('maven', 'self-hosted')
			implementationClass = 'foo.zaaarf.zipdist.ZipDistPlugin'
		}
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

tasks.withType(JavaCompile).configureEach {
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

gradlePlugin {
	website = 'https://zaaarf.foo/projects/zipdist/'
	vcsUrl = 'https://github.com/zaaarf/zipdist'
}
